[package]
name = "netifs-cli"
version = "0.2.0"
authors = ["Manuel Stocker <mensi@mensi.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netifs = "0.2.0"